import type { OwnerNotificationService, TelegramWebhookService } from "./user-services";
import type { UserStateRepository } from "../storage/user-state-repository";
import type { ApiTokenService, CreditService, GptHistoryService, UserService } from "./user-services";

interface TelegramUser { id: number; username?: string; first_name?: string; last_name?: string }
export interface TelegramWebhookUpdate {
  update_id?: number;
  pre_checkout_query?: { id: string; from?: TelegramUser };
  message?: { message_id?: number; text?: string; caption?: string; photo?: Array<{ file_id: string }>; successful_payment?: { invoice_payload?: string; total_amount?: number; telegram_payment_charge_id?: string }; from?: TelegramUser; chat?: { id: number } };
  callback_query?: { id: string; data?: string; from?: TelegramUser; message?: { message_id?: number; chat?: { id: number }; caption?: string } };
}

interface TelegramBotFlowDeps {
  db: D1Database;
  botToken: string;
  botUsername?: string;
  forceSubMode?: string;
  forceSubChannel?: string;
  forceSubInstagramUrl?: string;
  welcomeAudioFileId?: string;
  welcomeAudioKind?: "audio" | "voice" | "document";
  ownerTelegramChatId?: string;
  cardNumber?: string;
  ttsDemoAudiosJson?: string;
  users: UserService;
  credits: CreditService;
  tokens: ApiTokenService;
  history: GptHistoryService;
  userState: UserStateRepository;
  telegramEvents: TelegramWebhookService;
  ownerNotifications: OwnerNotificationService;
}

type InlineKeyboard = { inline_keyboard: Array<Array<{ text: string; callback_data?: string; url?: string }>> };
type ReplyKeyboard = { keyboard?: Array<Array<{ text: string }>>; resize_keyboard?: boolean; one_time_keyboard?: boolean; remove_keyboard?: boolean };
type ParseMode = "HTML" | "Markdown";

const nowTs = () => Math.floor(Date.now() / 1000);
const CREDIT_PER_CHAR = 1;
const GPT_MESSAGE_COST = 5;
const DAILY_REWARD_AMOUNT = 10;
const DAILY_REWARD_SECONDS = 24 * 60 * 60;

const LANGS: Array<[string, string]> = [["English", "en"], ["فارسی", "fa"], ["العربية", "ar"], ["Türkçe", "tr"], ["Русский", "ru"], ["Español", "es"], ["Deutsch", "de"], ["Français", "fr"]];
const STAR_PACKAGES = [{ stars: 250, credits: 8000, title: "• Starter " }, { stars: 1000, credits: 40000, title: "🎯 Creator " }, { stars: 3000, credits: 120000, title: "⚡️ Pro " }, { stars: 5500, credits: 300000, title: "👑 Studio" }];
const PAYMENT_PLANS = [{ title: " 800 → 150,000T", amount: 150000, credits: 800 }, { title: " 2899 → 340,000T", amount: 340000, credits: 2899 }, { title: " 6100 → 550,000T", amount: 550000, credits: 6100 }, { title: " 9200 → 770,000T", amount: 770000, credits: 9200 }, { title: " 12K + 1k → 999,000T", amount: 999000, credits: 13000 }, { title: " 21K → 1,650,000T", amount: 1650000, credits: 21000 }, { title: " 46K → 3,420,000T", amount: 3420000, credits: 46000 }, { title: " 88K → 5,990,000T", amount: 5990000, credits: 88000 }, { title: " 120K → 8,100,000T", amount: 8100000, credits: 120000 }, { title: " 150K → 9,999,000T", amount: 9999000, credits: 150000 }];
const DEFAULT_VOICE: Record<string, string> = { fa: "Liam", en: "Ava", ar: "Liam", tr: "Arda", ru: "Алина", es: "Valeria", de: "Lena", fr: "Léa" };
const VOICES: Record<string, string[]> = { fa: ["Liam", "Amir", "Nazy", "Sarah", "Alex", "Noushin", "Paniz", "Alexandra", "Laura", "Maxon", "Jessica", "Austin", "priyanka", "horatius", "anika", "brock", "Xavier", "Bradford"], en: ["Liam", "Noah", "Ava", "Nora", "Alex", "Ella", "Chloe", "Alexandra", "Laura", "Maxon", "Jessica", "Austin", "priyanka", "horatius", "anika", "brock", "Xavier", "Lucas"] };

const L: Record<string, Record<string, string>> = {
  home_title: { fa: "/help   منوی اصلی", en: "Main Menu" }, home_body: { fa: "یکی از گزینه‌های زیر را انتخاب کنید:", en: "Choose an option:" },
  btn_profile: { fa: "موجودی شما", en: "Your Balance" }, btn_credit: { fa: "خرید کردیـت 🛒", en: "Buy Credit 🛒" }, btn_tts: { fa: "تبدیل متن به صدا 🎧", en: "Text to Speech 🎧" }, btn_gpt: { fa: "GPT-5 mini 🫧", en: "GPT-5 mini 🫧" }, btn_lang: { fa: "Language 📚", en: "Language 📚" }, btn_invite: { fa: "🎁", en: "🎁" }, btn_clone: { fa: "ساخت صدای شخصی 🧬", en: "Voice Clone 🧬" },
  back: { fa: "🔙 بازگشت", en: "🔙 Back" }, home_back_to_menu: { fa: "🏠 منوی اصلی", en: "🏠 Main menu" }, lang_title: { fa: "انتخاب زبان", en: "Choose language" }, lang_hint: { fa: "یکی از زبان‌های زیر را انتخاب کن.", en: "Select one of the languages below." }, lang_saved: { fa: "✅ زبان ذخیره شد.", en: "✅ Language saved." },
  tts_title: { fa: "تبدیل متن به صدا 🎧", en: "AI Text to Speech " }, tts_prompt: { fa: "✨ <b>متن رو بفرست (هر کاراکتر = {credit} Credit)</b>", en: "✍🏼 Send your text (1 character = {credit} credit)" }, tts_demo: { fa: "▶︎ دمو", en: "▶︎ Demo" }, tts_output_mp3: { fa: "MP3 📁", en: "MP3 📁" }, tts_output_voice: { fa: "Voice 🎙️", en: "Voice 🎙️" }, tts_next: { fa: "بعدی ➜", en: "Next ➜" }, tts_prev: { fa: "⬅︎ قبل", en: "⬅︎ Previous" }, tts_no_credit: { fa: "⚠️ <b>کردیت کافی نیست</b>\n<b>موجودی شما: {credits} کردیت</b>\n<b>کردیت لازم: {required}</b>\n<b>می‌تونی کردیت بخری یا متن رو کوتاه‌تر کنی /help</b>", en: "⚠️ <b>Not enough credits</b>" },
  credit_title: { fa: "خرید کردیت", en: "Buy credits" }, credit_header: { fa: "برای استفاده از ربات، کردیت لازم دارید", en: "Pick a package below to top up your balance." }, credit_pay_stars_btn: { fa: "خرید با Telegram Stars 🌟", en: "Buy with Telegram Stars 🌟" }, credit_pay_rial_btn: { fa: "پرداخت به تومان", en: "Pay in Toman" }, credit_cancel: { fa: "لغو ❌", en: "Cancel ❌" }, credit_stars_menu: { fa: "🌟 شارژ آنی با Telegram Stars\n\nیکی از بسته‌های زیر را انتخاب کن:", en: "🌟 Instant top-up with Telegram Stars\n\nPick one of the packages below:" }, credit_invoice_label: { fa: "{credits} کردیت", en: "{credits} credits" }, credit_invoice_title: { fa: "Vexa — خرید کردیت", en: "Vexa — Buy Credits" }, credit_invoice_desc: { fa: "شارژ موجودی با Telegram Stars.", en: "Top up your balance with Telegram Stars." }, credit_pay_success: { fa: "✅ پرداخت موفق: ⭐{stars}\n🎉 {credits} کردیت اضافه شد.\n💳 موجودی: {balance}", en: "✅ Payment successful: ⭐{stars}" },
  invite_title: { fa: "🎁 دعوت دوستان", en: "🎁 Invite friends" }, invite_body: { fa: "لینک اختصاصی دعوت شما:\n{ref}\n\nپاداش هر دعوت موفق: <b>{bonus}</b> کردیت\nشناسه شما: <code>{user_id}</code>\nتعداد دعوت‌ها: <b>{invited}</b>", en: "Your invite link:\n{ref}" }, invite_daily_reward: { fa: "🎁 دریافت جایزه روزانه", en: "🎁 Daily reward" }, invite_daily_reward_success: { fa: "✅ {amount} کردیت هدیه گرفتی.", en: "✅ You received {amount} credits." }, invite_daily_reward_cooldown: { fa: "⏳ جایزه بعدی تا {time}", en: "⏳ Next reward in {time}" },
  gpt_open: { fa: "🤖 <b>چت GPT آماده است.</b>\nهر پیام {cost} کردیت هزینه دارد. سوالت را بفرست.\nبرای خروج دکمه پایان چت را بزن.", en: "🤖 <b>GPT chat is ready.</b>" }, gpt_end_button: { fa: "پایان چت GPT", en: "End GPT chat" }, gpt_end: { fa: "✅ چت GPT تمام شد.", en: "✅ GPT chat ended." }, gpt_wait: { fa: "در حال فکر کردن...", en: "Thinking..." }, gpt_no_credit: { fa: "⚠️ <b>کردیت کافی نیست</b>\n<b>موجودی: {balance}</b>\n<b>هزینه پیام: {cost}</b>", en: "⚠️ Not enough credits." }, gpt_not_configured: { fa: "⚠️ GPT هنوز روی Worker تنظیم نشده است.", en: "⚠️ GPT is not configured." }
};

const tt = (k: string, lang = "fa") => L[k]?.[lang] ?? L[k]?.fa ?? L[k]?.en ?? k;
const fill = (s: string, v: Record<string, string | number>) => Object.entries(v).reduce((a, [k, val]) => a.replaceAll(`{${k}}`, String(val)), s);
const chunks = <T>(a: T[], n: number) => Array.from({ length: Math.ceil(a.length / n) }, (_, i) => a.slice(i * n, i * n + n));
const fmtAmount = (n: number) => Number.isInteger(n) ? String(n) : String(n).replace(/\.0+$/, "");

function mainText(lang: string) { return `🏠 <b>${tt("home_title", lang)}</b>\n\n${tt("home_body", lang)}`; }
function mainMenu(lang: string): InlineKeyboard { return { inline_keyboard: [[{ text: tt("btn_profile", lang), callback_data: "home:profile" }, { text: tt("btn_credit", lang), callback_data: "home:credit" }], [{ text: tt("btn_tts", lang), callback_data: "home:tts" }], [{ text: tt("btn_gpt", lang), callback_data: "home:gpt_chat" }], [{ text: tt("btn_lang", lang), callback_data: "home:lang" }, { text: tt("btn_invite", lang), callback_data: "home:invite" }]] }; }
function langMenu(current: string, lang: string): InlineKeyboard { const rows = chunks(LANGS.map(([label, code]) => ({ text: `${code === current ? "• " : ""}${label}`, callback_data: `lang:set:${code}` })), 2); rows.push([{ text: tt("back", lang), callback_data: "lang:back" }]); return { inline_keyboard: rows }; }
function creditMenu(lang: string): InlineKeyboard { const rows = [[{ text: tt("credit_pay_stars_btn", lang), callback_data: "credit:stars" }]]; if (lang === "fa") rows.push([{ text: tt("credit_pay_rial_btn", lang), callback_data: "credit:payrial" }]); rows.push([{ text: tt("back", lang), callback_data: "home:back" }]); return { inline_keyboard: rows }; }
function starsMenu(lang: string): InlineKeyboard { const rows = chunks(STAR_PACKAGES.map(p => ({ text: p.title, callback_data: `credit:buy:${p.stars}:${p.credits}` })), 2); rows.push([{ text: tt("back", lang), callback_data: "credit:menu" }]); return { inline_keyboard: rows }; }
function rialMenu(lang: string): InlineKeyboard { const rows = chunks(PAYMENT_PLANS.map((p, i) => ({ text: p.title, callback_data: `credit:select:${i}` })), 2); rows.push([{ text: tt("back", lang), callback_data: "credit:menu" }]); return { inline_keyboard: rows }; }
function inviteMenu(lang: string): InlineKeyboard { return { inline_keyboard: [[{ text: tt("back", lang), callback_data: "home:back" }], [{ text: tt("invite_daily_reward", lang), callback_data: "invite:daily_reward" }]] }; }
function ttsText(lang: string, voice: string) { return `🎧 <b>${tt("tts_title", lang)}</b>\n\n${fill(tt("tts_prompt", lang), { credit: fmtAmount(CREDIT_PER_CHAR) })}\n\n🎙 <b>${voice}</b>`; }
function ttsMenu(lang: string, selected: string, page = 0, output: "mp3" | "voice" = "mp3"): InlineKeyboard { const names = VOICES[lang] ?? VOICES.fa; const cap = names.length > 10 ? 9 : 10; const total = Math.max(1, Math.ceil(names.length / cap)); const p = Math.max(0, Math.min(page, total - 1)); const pageNames = names.slice(p * cap, p * cap + cap); const rows = chunks(pageNames.map(n => ({ text: `${n === selected ? "✔️ " : ""}${n}`, callback_data: `tts:voice:${n}` })), 2); const nav = []; if (names.length > 10 && p > 0) nav.push({ text: tt("tts_prev", lang), callback_data: "tts:page:prev" }); if (names.length > 10 && p < total - 1) nav.push({ text: tt("tts_next", lang), callback_data: "tts:page:next" }); if (nav.length) rows.push(nav); rows.push([{ text: tt("tts_demo", lang), callback_data: `tts:demo:${selected}` }]); rows.push([{ text: `${output === "mp3" ? "✔️ " : ""}${tt("tts_output_mp3", lang)}`, callback_data: "tts:output:mp3" }, { text: `${output === "voice" ? "✔️ " : ""}${tt("tts_output_voice", lang)}`, callback_data: "tts:output:voice" }]); rows.push([{ text: tt("btn_clone", lang), callback_data: "home:clone" }]); rows.push([{ text: tt("back", lang), callback_data: "home:back" }]); return { inline_keyboard: rows }; }
function backHome(lang: string): InlineKeyboard { return { inline_keyboard: [[{ text: tt("home_back_to_menu", lang), callback_data: "home:back" }]] }; }

export class TelegramBotFlowService {
  constructor(private deps: TelegramBotFlowDeps) {}
  async handleWebhook(update: TelegramWebhookUpdate) { const uid = update.message?.from?.id ?? update.callback_query?.from?.id ?? update.pre_checkout_query?.from?.id ?? null; if (await this.deps.telegramEvents.shouldSkipUpdate(update.update_id)) return { ok: true, skipped: true }; if (update.pre_checkout_query) await this.call("answerPreCheckoutQuery", { pre_checkout_query_id: update.pre_checkout_query.id, ok: true }); else if (update.callback_query) await this.onCallback(update.callback_query); else if (update.message) await this.onMessage(update.message); if (update.update_id !== undefined) await this.deps.telegramEvents.markProcessed(update.update_id, uid, update.callback_query ? "callback_query" : "message"); return { ok: true }; }
  private async user(from: TelegramUser) { const u = await this.deps.users.bootstrapTelegramUser({ userId: from.id, username: from.username ?? null, firstName: from.first_name ?? null }); await this.deps.users.touchLastSeen(from.id); return u; }
  private async onMessage(m: NonNullable<TelegramWebhookUpdate["message"]>) { if (!m.from || !m.chat) return; const u = await this.user(m.from); const lang = u.lang || "fa"; const text = (m.text || "").trim(); const state = await this.deps.userState.getBotState(u.userId); if (m.successful_payment) return this.successPay(m, u.userId, lang); if (text.startsWith("/start") || text === "/menu") return this.home(m.chat.id, u.userId, lang, m.message_id); if (state.mode === "tts:wait_text" && text) return this.say(m.chat.id, fill(tt("tts_no_credit", lang), { credits: (await this.deps.credits.getCredits(u.userId)).credits, required: text.length }), { parse_mode: "HTML", reply_markup: { inline_keyboard: [[{ text: tt("btn_credit", lang), callback_data: "credit:menu" }]] } }); if (state.mode === "gpt:chat" && text) return this.gptText(m.chat.id, u.userId, lang, text); return this.home(m.chat.id, u.userId, lang, m.message_id); }
  private async onCallback(c: NonNullable<TelegramWebhookUpdate["callback_query"]>) { if (!c.from || !c.message?.chat) return; const u = await this.user(c.from); const lang = u.lang || "fa"; const chat = c.message.chat.id; const msg = c.message.message_id; const d = c.data || ""; await this.call("answerCallbackQuery", { callback_query_id: c.id }); if (d === "home:back" || d === "lang:back") return this.home(chat, u.userId, lang, msg); if (d === "home:profile") return this.profile(chat, msg, u.userId, lang); if (d === "home:tts") return this.openTts(chat, msg, u.userId, lang); if (d === "home:credit" || d === "credit:menu") return this.edit(chat, msg, `🛒 <b>${tt("credit_title", lang)}</b>\n\n${tt("credit_header", lang)}`, creditMenu(lang)); if (d === "credit:stars") return this.edit(chat, msg, tt("credit_stars_menu", lang), starsMenu(lang)); if (d === "credit:payrial") return this.edit(chat, msg, "🧾 <b>پرداخت به تومـان – انتخاب پلن</b>\n\nبا خرید هر بسته 30% کردیت بیشتر دریافت میکنید\nیکی از بسته‌های زیر را انتخاب کنید:", rialMenu(lang)); if (d.startsWith("credit:buy:")) return this.buyStars(u.userId, lang, d); if (d === "home:lang") return this.edit(chat, msg, `🌐 <b>${tt("lang_title", lang)}</b>\n\n${tt("lang_hint", lang)}`, langMenu(lang, lang)); if (d.startsWith("lang:set:")) return this.setLang(chat, msg, u.userId, d.split(":")[2] || "fa"); if (d === "home:invite") return this.invite(chat, msg, u.userId, lang); if (d === "invite:daily_reward") return this.daily(c.id, u.userId, lang); if (d === "home:gpt_chat") return this.openGpt(chat, msg, u.userId, lang); if (d.startsWith("tts:")) return this.ttsCallback(chat, msg, u.userId, lang, d); }
  private async home(chat: number, userId: number, lang: string, msg?: number) { await this.deps.userState.setBotState(userId, { mode: "idle", updatedAt: nowTs() }); return this.edit(chat, msg, mainText(lang), mainMenu(lang)); }
  private async profile(chat: number, msg: number | undefined, userId: number, lang: string) { const b = await this.deps.credits.getCredits(userId); return this.edit(chat, msg, `💳 <b>${tt("btn_profile", lang)}</b>\n\n${b.credits} Credit`, backHome(lang)); }
  private async setLang(chat: number, msg: number | undefined, userId: number, lang: string) { await this.deps.users.setLanguage(userId, lang); return this.edit(chat, msg, tt("lang_saved", lang), mainMenu(lang)); }
  private async invite(chat: number, msg: number | undefined, userId: number, lang: string) { const ref = `https://t.me/${this.deps.botUsername || "VexaBot"}?start=${userId}`; return this.edit(chat, msg, `🎁 <b>${tt("invite_title", lang)}</b>\n\n${fill(tt("invite_body", lang), { ref, bonus: 30, user_id: userId, invited: 0 })}`, inviteMenu(lang)); }
  private async daily(id: string, userId: number, lang: string) { const st = await this.deps.userState.getBotState(userId); const last = st.dailyRewardClaimedAt || 0; const now = nowTs(); if (now - last >= DAILY_REWARD_SECONDS) { await this.deps.credits.grant(userId, DAILY_REWARD_AMOUNT, "daily_reward", "telegram_bot"); await this.deps.userState.setBotState(userId, { ...st, dailyRewardClaimedAt: now, updatedAt: now }); return this.call("answerCallbackQuery", { callback_query_id: id, text: fill(tt("invite_daily_reward_success", lang), { amount: DAILY_REWARD_AMOUNT }), show_alert: true }); } const rem = DAILY_REWARD_SECONDS - (now - last); return this.call("answerCallbackQuery", { callback_query_id: id, text: fill(tt("invite_daily_reward_cooldown", lang), { time: `${String(Math.floor(rem / 3600)).padStart(2, "0")}:${String(Math.floor((rem % 3600) / 60)).padStart(2, "0")}` }), show_alert: true }); }
  private async openTts(chat: number, msg: number | undefined, userId: number, lang: string) { const voice = DEFAULT_VOICE[lang] || "Liam"; await this.deps.userState.setBotState(userId, { mode: "tts:wait_text", updatedAt: nowTs(), ttsVoice: voice, ttsOutput: "mp3", ttsPage: 0 }); return this.edit(chat, msg, ttsText(lang, voice), ttsMenu(lang, voice)); }
  private async ttsCallback(chat: number, msg: number | undefined, userId: number, lang: string, d: string) { const st = await this.deps.userState.getBotState(userId); let v = st.ttsVoice || DEFAULT_VOICE[lang] || "Liam"; let p = st.ttsPage || 0; let o = st.ttsOutput || "mp3"; if (d.startsWith("tts:voice:")) v = d.split(":").slice(2).join(":"); if (d === "tts:page:next") p += 1; if (d === "tts:page:prev") p = Math.max(0, p - 1); if (d === "tts:output:mp3") o = "mp3"; if (d === "tts:output:voice") o = "voice"; if (d.startsWith("tts:demo:")) return this.say(chat, "❌ دموی این صدا هنوز تنظیم نشده است."); await this.deps.userState.setBotState(userId, { ...st, mode: "tts:wait_text", ttsVoice: v, ttsOutput: o, ttsPage: p, updatedAt: nowTs() }); return this.edit(chat, msg, ttsText(lang, v), ttsMenu(lang, v, p, o)); }
  private async openGpt(chat: number, msg: number | undefined, userId: number, lang: string) { await this.deps.userState.setBotState(userId, { mode: "gpt:chat", updatedAt: nowTs() }); return this.editOrSend(chat, msg, fill(tt("gpt_open", lang), { cost: GPT_MESSAGE_COST }), undefined, { keyboard: [[{ text: tt("gpt_end_button", lang) }]], resize_keyboard: true }); }
  private async gptText(chat: number, userId: number, lang: string, text: string) { if (text === tt("gpt_end_button", lang)) { await this.deps.userState.setBotState(userId, { mode: "idle", updatedAt: nowTs() }); await this.say(chat, tt("gpt_end", lang), { parse_mode: "HTML", reply_markup: { remove_keyboard: true } }); return this.home(chat, userId, lang); } return this.say(chat, tt("gpt_not_configured", lang), { parse_mode: "HTML" }); }
  private async buyStars(chat: number, lang: string, d: string) { const parts = d.split(":"); const stars = Number(parts[2]); const credits = Number(parts[3]); return this.call("sendInvoice", { chat_id: chat, title: tt("credit_invoice_title", lang), description: tt("credit_invoice_desc", lang), payload: JSON.stringify({ credits }), provider_token: "", currency: "XTR", prices: [{ label: fill(tt("credit_invoice_label", lang), { credits }), amount: stars }] }); }
  private async successPay(m: NonNullable<TelegramWebhookUpdate["message"]>, userId: number, lang: string) { const p = JSON.parse(m.successful_payment?.invoice_payload || "{}"); const credits = Number(p.credits || 0); const stars = Number(m.successful_payment?.total_amount || 0); if (credits > 0) await this.deps.credits.grant(userId, credits, "telegram_stars_payment", "telegram_bot"); const b = await this.deps.credits.getCredits(userId); return this.say(m.chat!.id, fill(tt("credit_pay_success", lang), { stars, credits, balance: b.credits }), { parse_mode: "HTML" }); }
  private async edit(chat: number, msg: number | undefined, text: string, kb?: InlineKeyboard) { return this.editOrSend(chat, msg, text, kb); }
  private async say(chat: number | string, text: string, opts: { parse_mode?: ParseMode; reply_markup?: unknown } = {}) { return this.call("sendMessage", { chat_id: chat, text, ...opts }); }
  private async editOrSend(chat: number, msg: number | undefined, text: string, inline?: InlineKeyboard, reply?: ReplyKeyboard) { const rm = inline || reply; if (msg && inline) { const edited = await this.call("editMessageText", { chat_id: chat, message_id: msg, text, parse_mode: "HTML", reply_markup: rm }); if (edited.ok) return edited; } return this.say(chat, text, { parse_mode: "HTML", reply_markup: rm }); }
  private async call(method: string, body: Record<string, unknown>): Promise<{ ok?: boolean; result?: { message_id?: number } }> { const base = "https://api.telegram.org/"; const res = await fetch(`${base}bot${this.deps.botToken}/${method}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); return (await res.json().catch(() => ({ ok: false }))) as { ok?: boolean; result?: { message_id?: number } }; }
}
